spring.application.name=gestor-pedidos-miel

# Configuracion del Servidor (el programa corre aqui)
server.port=8080
spring.main.web-application-type=none

# WooCommerce configuration
woocommerce.store-url=${STORE_URL}
woocommerce.consumer-key=${WOO_CONSUMER_KEY}
woocommerce.consumer-secret=${WOO_CONSUMER_SECRET}

# Telegram configuration
telegram.token=${TELEGRAM_TOKEN}
telegram.token-preparados=${TELEGRAM_PREPARADOS}
telegram.token-disposicion=${TELEGRAM_DISPOSICION}
telegram.token-no-enviados=${TELEGRAM_NOENVIADOS}
telegram.token-alertas=${TELEGRAM_ALERTAS}
telegram.token-estacionados=${TELEGRAM_ESTACIONADOS}
telegram.chat-id=${TELEGRAM_CHAT_ID}
telegram.telefono-oficial=${TELEFONO_OFICIAL}

# Product label mappings
correos.product-labels[48]=Bos 
correos.product-labels[50]=Br 
correos.product-labels[61]=x(3TL-3Bos) 
correos.product-labels[62]=x(6Br) 
correos.product-labels[63]=x(6Bos) 
correos.product-labels[143]=Tintu 
correos.product-labels[145]=x(3Bos-3Br) 
correos.product-labels[146]=Polen 
correos.product-labels[242]=TL 
correos.product-labels[331]=Cant 
correos.product-labels[339]=x(6Cant) 
correos.product-labels[374]=x(6TL) 
correos.product-labels[384]=Palito 
correos.product-labels[393]=x(2Br-2Bos-2Cant) 
correos.product-labels[1190]=x(2Br-2Bos-2TL) 
correos.product-labels[1861]=PropoleoCrudo 
correos.product-labels[1863]=Cera 
correos.product-labels[1865]=Cesta 


