spring.application.name=gestor-pedidos-miel

# Configuración del Servidor (el programa corre aquí)
server.port=8080

# Mis claves de WooCommerce
woocommerce.url=https://mielpanera.com
woocommerce.key=ck_XXXXXXXXXXXXXXXXXXXXXXXX
woocommerce.secret=cs_XXXXXXXXXXXXXXXXXXXXXXXX